### ISSUE TITLE
i am a Student.   I've read your work carefully and think it's very impressive.

### ISSUE THREAD

**Issue by coraler** [delta2323/gnn-asymptotics#3]
But I do not understand a place, I hope to help me to solve.   "For any X ∈ M, if two nodes i, j ∈ V are in a same connected
component and their degrees are identical, then, the column vectors of X that correspond to nodes i
and j are identical."   The words above are from the paper, i dont understand that the meaning of it. Is it that the nodes with the same degree carry the same feature, or that the feature carried by the nodes are all the same.

**Comment by delta2323** [comment]
Thank you for taking your interest in the paper and giving us questions.

>  Is it that the nodes with the same degree carry the same feature, or that the feature carried by the nodes are all the same.

We intended to mean the former one. Let $X=(X_{nc}) \in M \subset R^{N\times C}$ be a collection of node representations, where $N$ and $C$ are sample and channel sizes, respectively. The sentence means that if node $i$ and $j$ have the same node degree and are in the same connected component, then we have $X_{i} = X_{c}\in R^C$.

**Comment by coraler** [comment]
Thank you very much for your explanation.

**Comment by delta2323** [comment]
You are welcome. Let me close this issue. Feel free to reopen it if you have more questions. Thank you.

**Comment by phucdoitoan** [comment]
@coraler I just want to add up a little bit to @delta2323 's answer. At infinity, the node features approach the subspace U, whose basis vectors are e_m = \tilde{D}^{1/2} u_m as stated in Proposition 1. The basis e_m only depends on node degrees \tilde{D} and connected components indicator u_m. Therefore, at infinity, nodes with the same degrees in the same connected component will have the same features.
